### ISSUE TITLE
Calendars View - Add upload button

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder#1]
icon_upload.svg
To the right of Edit button.
Direct to Luminous Shard with Self-Report details filled out.

**Comment by arapawa** [comment]
Only AM has final say for uploads to Limeade.

**Comment by arapawa** [comment]
@arapawa Do an A/B test to see if the current icon or an up-arrow will be more intuitive.

**Comment by dannytpeck** [comment]
Aaaaall good now
af534d2
