### ISSUE TITLE
Add the link/share button to the Client Calendars view

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder#16]
Put the Link/Share icon between the Edit and Airplane icons.

The icon is in images/icon_link.svg.

**Comment by arapawa** [comment]
@dannytpeck I added the icon as part of https://github.com/dannytpeck/calendar-builder/pull/17 but haven't hooked it up to pull data in and launch the comment/whatever box like in
![calendar-link](https://user-images.githubusercontent.com/16523445/43293656-406b2eec-90f0-11e8-999e-0bc790883458.png)

**Comment by dannytpeck** [comment]
61d468f5f

**Comment by dannytpeck** [comment]
Straight fire 🔥
