### ISSUE TITLE
Update Phase date logic

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder#19]
Instead of hardcoded.

Algorithm is:

1.) Program years should be considered to be 48-49 weeks (full year, i.e. 52 weeks minus 2-3 weeks of maintainence)

2.) Phases start on Mondays (this is important for weekly challenge/goal tracking in Limeade). 

3.) Phases end on Sundays (this is important for weekly challenge/goal tracking in Limeade). 

4.) Primary phases (e.g. Phase 1) run between 11-13 weeks. The # of week logic is determined by the determined phase dates (see separate tab, also screenshot attached) : Phase end date minus phase start date (# of days) / 7. 

5.) Secondary phase dates (e.g. Phase 1B) has the same logic as #4. These phases start ~1 month into the primary phase. 

6.) Year-long = the start date is the same as the start date of the challenges in Phase 1 ; end date is the same as the end date of Phase 4 challenges.

[2018 ADURO Platform Challenge Calendar_FINAL.xlsx](https://github.com/dannytpeck/calendar-builder/files/2294731/2018.ADURO.Platform.Challenge.Calendar_FINAL.xlsx)

![phase-table](https://user-images.githubusercontent.com/16523445/44226572-507d3b80-a145-11e8-984b-e19ef7afc0e3.png)

**Comment by dannytpeck** [comment]
b456a9895
