### ISSUE TITLE
Edit Calendar View - Change Pencil icon to Save icon when editing

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/calendar-builder#4]

**Comment by dannytpeck** [comment]
@arapawa Do we have a save icon for this?

**Comment by arapawa** [comment]
@dannytpeck We do now! Added in f31a3ff .

**Comment by dannytpeck** [comment]
@arapawa I refuse to call it a Save Icon for some reason LOL

Resolved in a6f96c2

👵 💾 💍 👴
